# Generated by Django 4.0.5 on 2022-08-08 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistermodel',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='userregistermodel',
            name='password2',
        ),
    ]
